#-------------------------------------------------------------
# This file is automatically generated by the Matlab function:
# runThirdStageCleaningREddyProc.m
# 03-Feb-2023 14:10:57
#--------------------------------------------------------------
site    <- "YOUNG"
yrs     <- 2022
db_root <- "/Users/darianng/Documents/MSc_Geography/Biomet_cleaning/Local_copies"
fx_path <- "/Users/darianng/Documents/MSc_Geography/Biomet.net/R/database_functions"
Ustar_scenario <- "fast"
do_REddyProc   <- 1
yearsToProcess <- 2
pthDatabase    <- "/Users/darianng/Documents/MSc_Geography/Biomet_cleaning/Local_copies"
pthBiometR     <- "/Users/darianng/Documents/MSc_Geography/Biomet.net/R/database_functions"
pthLogFile     <- "/Users/darianng/Documents/MSc_Geography/Biomet_cleaning/Local_copies/Calculation_Procedures/TraceAnalysis_ini/Young/log/YOUNG_ThirdStageCleaning.log"
ini_path       <- "/Users/darianng/Documents/MSc_Geography/Biomet_cleaning/Local_copies/Calculation_Procedures/TraceAnalysis_ini/Young"

args <-c("/Users/darianng/Documents/MSc_Geography/Biomet.net/R/database_functions", "/Users/darianng/Documents/MSc_Geography/Biomet_cleaning/Local_copies/Calculation_Procedures/TraceAnalysis_ini/Young/log/YOUNG_setThirdStageCleaningParameters.R")
# source("/Users/darianng/Documents/MSc_Geography/Biomet.net/R/database_functions/Run_ThirdStage_REddyProc.R")
