REM ----------------------------------------------------------
REM  This file is automatically generated by Matlab function:
REM  runThirdStageCleaningREddyProc.m
REM  14-Feb-2023 10:37:18
REM ----------------------------------------------------------
"C:\Program Files\R\R-4.2.1\bin\Rscript.exe" "C:/Biomet.net/R/database_functions/Run_ThirdStage_REddyProc.R" "C:/Biomet.net/R/database_functions" "p:\database\Calculation_Procedures\TraceAnalysis_ini\DSM\log\DSM_setThirdStageCleaningParameters.R"  2> "p:/database/Calculation_Procedures/TraceAnalysis_ini/DSM/log/DSM_ThirdStageCleaning.log" 1>&2
