#-------------------------------------------------------------
# This file is automatically generated by the Matlab function:
# runThirdStageCleaningREddyProc.m
<<<<<<< HEAD
# 09-Feb-2023 19:38:57
=======
# 02-Mar-2023 09:32:21
>>>>>>> main
#--------------------------------------------------------------
site    <- "DSM"
yrs     <- 2022
db_root <- "C:/Users/User/PostDoc_Work/database"
fx_path <- "C:/Biomet.net/R/database_functions"
Ustar_scenario <- "fast"
do_REddyProc   <- 1
yearsToProcess <- 2
pthDatabase    <- "C:/Users/User/PostDoc_Work/database"
pthBiometR     <- "C:/Biomet.net/R/database_functions"
pthLogFile     <- "C:/Users/User/PostDoc_Work/database/Calculation_Procedures/TraceAnalysis_ini/DSM/log/DSM_ThirdStageCleaning.log"
ini_path       <- "C:/Users/User/PostDoc_Work/database/Calculation_Procedures/TraceAnalysis_ini/DSM"
