#-------------------------------------------------------------
# This file is automatically generated by the Matlab function:
# runThirdStageCleaningREddyProc.m
# 07-Mar-2023 17:29:23
#--------------------------------------------------------------
site    <- "HOGG"
yrs     <- 2021
db_root <- "p:/database"
fx_path <- "C:/Biomet.net/R/database_functions"
Ustar_scenario <- "fast"
do_REddyProc   <- 1
yearsToProcess <- 2
pthDatabase    <- "p:/database"
pthBiometR     <- "C:/Biomet.net/R/database_functions"
pthLogFile     <- "p:/database/Calculation_Procedures/TraceAnalysis_ini/HOGG/log/HOGG_ThirdStageCleaning.log"
ini_path       <- "p:/database/Calculation_Procedures/TraceAnalysis_ini/HOGG"
