#-------------------------------------------------------------
# This file is automatically generated by the Matlab function:
# runThirdStageCleaningREddyProc.m
# (manually by Ted on 2023-10-27)
#--------------------------------------------------------------
data_source <- "Micromet"
site    <- "OHM"
yrs     <- 2023
db_root <- "/Users/tedscott/Matlab/local_data_cleaning/Database"
fx_path <- "/Users/tedscott/Biomet.net/R/database_functions"
Ustar_scenario <- "fast"
do_REddyProc   <- 1
yearsToProcess <- 1
pthDatabase    <- "/Users/tedscott/Matlab/local_data_cleaning/Database"
pthBiometR     <- "/Users/tedscott/Biomet.net/R/database_functionss"
pthLogFile     <- "/Users/tedscott/Matlab/local_data_cleaning/Database/Calculation_Procedures/TraceAnalysis_ini/OHM/log/OHM_ThirdStageCleaning.log"
ini_path       <- "/Users/tedscott/Matlab/local_data_cleaning/Database/Calculation_Procedures/TraceAnalysis_ini/OHM"
