#-------------------------------------------------------------
# This file is automatically generated by the Matlab function:
# runThirdStageCleaningREddyProc.m
# 02-Feb-2023 14:08:47
#--------------------------------------------------------------
site    <- "BB"
yrs     <- 2021
db_root <- "C:/Users/User/PostDoc_Work/database"
fx_path <- "C:/Biomet.net/R/database_functions"
Ustar_scenario <- "fast"
do_REddyProc   <- 1
yearsToProcess <- 2
pthDatabase    <- "C:/Users/User/PostDoc_Work/database"
pthBiometR     <- "C:/Biomet.net/R/database_functions"
pthLogFile     <- "C:/Users/User/PostDoc_Work/database/Calculation_Procedures/TraceAnalysis_ini/BB/log/BB_ThirdStageCleaning.log"
ini_path       <- "C:/Users/User/PostDoc_Work/database/Calculation_Procedures/TraceAnalysis_ini/BB"
