REM ----------------------------------------------------------
REM  This file is automatically generated by Matlab function:
REM  runThirdStageCleaningREddyProc.m
REM  01-Feb-2023 13:12:27
REM ----------------------------------------------------------
"C:\Program Files\R\R-4.1.0\bin\Rscript.exe" "C:/Biomet.net/R/database_functions/Run_ThirdStage_REddyProc.R" "C:/Biomet.net/R/database_functions" "C:\Users\User\PostDoc_Work\database\Calculation_Procedures\TraceAnalysis_ini\BB\log\BB_setThirdStageCleaningParameters.R"  2> "C:/Users/User/PostDoc_Work/database/Calculation_Procedures/TraceAnalysis_ini/BB/log/BB_ThirdStageCleaning.log" 1>&2
